version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/dbname  # MySQL database connection URL

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root  # MySQL root password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
